routes/web.php
<?php
use App\Http\Controllers\AnswerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\TagController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [HomeController::class, 'index'])->name('home');
Auth::routes();
// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// Route::resource('/question',QuestionController::class);
// Route::resource('/tag',TagController::class);
Route::group(['middleware' => 'auth'], function () {
    Route::resource('/question', QuestionController::class);
    Route::get('/questions/votes/{id?}', [App\Http\Controllers\QuestionController::class,'questionCastVote'])->name('question.votes');
    Route::get('/answers/votes/{id?}', [QuestionController::class, 'answerCastVote'])->name('answers.votes');
    Route::resource('/tag', TagController::class);
    Route::post('/store', [AnswerController::class, 'storeAnswer'])->name('submit');
    Route::get('/answers/{id}/edit', [AnswerController::class, 'editAnswer'])->name('answers');
    Route::post('accept-answer/{id}', [AnswerController::class, 'acceptAnswer'])->name('accept-answer');
    Route::put('/answersupdate/{id}', [AnswerController::class, 'updateAnswer'])->name('answers-update');
    Route::delete('/deleteanswer/{id}', [AnswerController::class, 'answerDelete'])->name('delete-answer');
});

resources/views/ask-questions.blade.php
@extends('layouts.admin.app')
@section('content')
    <div class="container pt-4">
        <h1 class="mt-4">Ask Public Questions</h1>
        <ol class="breadcrumb mb-4">
            <a class="btn btn-primary" href="{{ url('/') }}"> Back</a>
        </ol>
        <div class="card">
            <form action=" {{ route('question.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="card-body">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <label for="title"><strong>Title <span class="text-danger">*</span></strong></label>
                            <input type="text" id="title" name="title" class="form-control"
                                placeholder="Enter Title">
                            @if ($errors->has('title'))
                                <span class="text-danger">{{ $errors->first('title') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <label for="body"><strong>Body <span class="text-danger">*</span></strong></label>
                            <textarea class="ckeditor form-control" name="body" required></textarea>
                            @if ($errors->has('body'))
                                <span class="text-danger">{{ $errors->first('body') }}</span>
                            @endif
                        </div>
                    </div>
                    {{-- dd($tags) --}}
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <label for="question_tag"><strong>Select Tags <span
                                        class="text-danger">*</span></strong></label>
                            <select class="js-example-basic-multiple o100 form-control" name="question_tag[]"
                                multiple="multiple">
                                <option class="o100" value="" disabled>Select tag</option>
                                @foreach ($tags as $tag)
                                    <option class="fc-black-900" value="{{ $tag->tag }}">{{ $tag->tag }}</option>
                                @endforeach
                            </select>
                            @if ($errors->has('question_tag'))
                                <span class="text-danger">{{ $errors->first('question_tag') }}</span>
                            @endif
                            <ol class="breadcrumb h16 pt-0 pl-1">
                                Select tags according to your question.
                            </ol>
                        </div>
                    </div>
                </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Review Your Question</button>
        </div>
        </form>
    </div>
    @endsection
    @section('footer-scripts')
    {{-- --}}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('.js-example-basic-multiple').select2();
                // $('.ckeditor');
        });
    </script>
    @endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/question-edit.blade.php
@extends('layouts.admin.app')
@section('content')
<div class="container pt-4">
    <h1 class="mt-4">Edit Questions</h1>
    <ol class="breadcrumb mb-4">
        <a class="btn btn-primary" href="{{ route('home') }}"> Back</a>
    </ol>
    <div class="card">
        <form action=" {{ route('question.update', $question->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="card-body">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="title"><strong>Title <span class="text-danger">*</span></strong></label>
                        <input type="text" id="title" name="title" class="form-control" value="{{ $question->title }}">
                        @if ($errors->has('title'))
                        <span class="text-danger">{{ $errors->first('title') }}</span>
                        @endif
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="body"><strong>Body <span class="text-danger">*</span></strong></label>
                        <textarea class="ckeditor form-control" id="body" name="body"
                            value="{{ $question->body }} "> {{ $question->body }}</textarea>
                        @if ($errors->has('body'))
                        <span class="text-danger">{{ $errors->first('body') }}</span>
                        @endif
                    </div>
                </div>
                {{-- {{ dd($tags) }} --}}
                @php
                // $dbtag= $question->tag->pluck('id')->toArray()
                $dbtag = explode('"', $question->question_tag);
                @endphp
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="question_tag">
                            <strong>Select Tags 
                                <span class="text-danger">*</span>
                            </strong>
                        </label>
                        <select class="js-example-basic-multiple o100 form-control" name="question_tag[]" multiple="multiple">
                            <option class="o100" value="" disabled>Select tag</option>
                            @foreach ($tags as $tag)
                            <option class="fc-black-900" value="{{ $tag->tag }}"@if (in_array($tag->tag, $dbtag)) selected @endif>{{ $tag->tag }}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('question_tag'))
                        <span class="text-danger">{{ $errors->first('question_tag') }}</span>
                        @endif
                        <ol class="breadcrumb h16 pt-0 pl-1">
                            Select tags according to your question.
                        </ol>
                    </div>
                </div>
            </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Review Your Question</button>
    </div>
    </form>
</div>
@endsection
@section('footer-scripts')
{{-- --}}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
                    $('.js-example-basic-multiple').select2();
                        // $('.ckeditor');
                });
</script>
@endsection

resources/views/questions.blade.php
@extends('layouts.admin.app')
@section('content')
    @if ($message = Session::get('success'))
        <div>
            <div class="alert alert-success mt-3">
                <p>{{ $message }}</p>
            </div>
        </div>
    @endif
    <div class="container">
        <h1 class="pt-2">All Question </h1>
        <ol class="s-breadcrumbs mb-4">
            {{ now()->toDateTimeString() }}
        </ol>
        <!-- Serach bar and sorting-->
        <header class="s-topbar">
            <form id="search" class="s-topbar--searchbar" action="" method="GET" autocomplete="off">
                <div class="s-select">
                    <input type="hidden" id="orderby" name="sort" value="{{ $sort }}">
                    <select id="ordering" name="order">
                        <option value="" disabled >select sorting</option>
                        <option value="asc">A-Z</option>
                        <option value="desc">Z-A</option>
                    </select>
                </div>
                <div class="s-topbar--searchbar--input-group">
                    <input class="s-input s-input__search" type="text" name="search" placeholder="Search....."
                        value="{!! request('search') !!}" />
                </div>
            </form>
        </header>
        <script>
            $(document).ready(function() {
                $('#ordering').on("change", function() { // for id #
                    $('#orderby').val($(this).val());
                    $('#search').submit();
                });
            });
        </script>
        <!--create Question Start---->
        <ol class="s-breadcrumb mb-2 mt-2">
            <a href="{{ route('question.create') }}" class="btn btn-primary mt-2"> Ask Question</a>
        </ol>
    @foreach ($questions as $question)
        <div class="s-post-summary">
            <div class="s-post-summary--stats">
                <div class="s-post-summary--stats-item s-post-summary--stats-item__emphasized">
                    <span class="s-post-summary--stats-item-number">
                        {{ $question->count }}
                    </span>
                    <span class="s-post-summary--stats-item-unit">
                        votes
                    </span>
                </div>
                <div class="s-post-summary--stats-item has-answers has-accepted-answer">
                    <span class="s-post-summary--stats-item-number">
                        {{ (count($question->answer)) }}
                    </span>
                    <span class="s-post-summary--stats-item-unit">
                        answers
                    </span>
                </div>
                <div class="s-post-summary--stats-item is-supernova">
                    <span class="s-post-summary--stats-item-number">
                        {{ count($question->questionview) }}
                    </span>
                    <span class="s-post-summary--stats-item-unit">
                        views
                    </span>
                </div>
            </div>
            <div class="s-post-summary--content">
                <div class="s-post-summary--content-type">
                    <a href="…" class="s-link s-link__grayscale">
                    </a>
                </div>
                <h3 class="s-post-summary--content-title">
                    <a title="{{ $question->title }}" href="{{ route('question.show', $question->id) }}" class="s-link">
                        {{ $question->title }}
                    </a>
                </h3>
                <!-- <details> -->
                <!-- <summary>Click here</summary> -->
                <p class="s-post-summary--content-excerpt">
                    {!! Str::limit($question->body, 200) !!}
                </p>
                <!-- </details> -->
                <div class="s-post-summary--meta">
                    <div class="s-post-summary--meta-tags">
                        @php
                            $t=explode('"',$question->question_tag);
                            $res = str_replace( array( ',','"','[',']' ), '' , $t); // Returning the result return $res;
                            $tags=array_filter($res);
                            // dd($r);
                            // $tags=explode(',',$t);
                        @endphp
                        @foreach ($tags as $tag)
                        <a class="s-tag" href="#">
                            {{ $tag }}
                        </a>
                        @endforeach
                    </div>
                    <div class="s-post-summary--meta mt-4">
                        <div class="s-post-summary--meta-tags">
                            <strong> Created By:</strong>
                            <a href="#">
                                {{ $question->user->name }}
                            </a>
                            <time class="s-user-card--time">
                                {{ $question->created_at }}
                            </time>
                        </div>
                    </div>
                </div>
            </div>
            <span class="">
           @if ($question->user_id == auth()->id())
                <!-- <a href="https://demo.getcraftable.com/admin/tags/3/edit" title="Edit" role="button" class="btn btn-sm btn-spinner btn-info"><i class="fa fa-edit"></i></a> -->
                <a class="btn btn-primary" title="you can edit your question" href="{{ route('question.edit', $question->id) }}">
                    <i class="fas fa-edit" aria-hidden="true"></i></a>
                <form action="{{ route('question.destroy', $question->id) }}" method="POST">
                    <input name="_method" type="hidden" value="DELETE">
                    <button title="your question will be deleted permenantly" type="submit"
                        class="mt-2 mb-2 btn btn-danger btn-flat show_confirm" data-toggle="tooltip" title='Delete'>
                        <i class="far fa-trash-alt"></i>
                    </button>
                    @csrf
                    @method('DELETE')
                </form>
            @endif
            </span>
        </div>
    @endforeach
    {{-- {!! $questions->appends(Request::except('page'))->render() !!} --}}
    {{-- !! $questions->render() !! --}}
    {{ $questions->links() }}
    <p>
        Displaying
        {{ $questions->count() }}
        of
        {{ $questions->total() }}
        Questions(s).
    </p>
    </div>
@endsection