routes/web.php
<?php
use App\Http\Controllers\AnswerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\TagController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [HomeController::class, 'index'])->name('home');
Auth::routes();
// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// Route::resource('/question',QuestionController::class);
// Route::resource('/tag',TagController::class);
Route::group(['middleware' => 'auth'], function () {
    Route::resource('/question', QuestionController::class);
    Route::get('/questions/votes/{id?}', [App\Http\Controllers\QuestionController::class,'questionCastVote'])->name('question.votes');
    Route::get('/answers/votes/{id?}', [QuestionController::class, 'answerCastVote'])->name('answers.votes');
    Route::resource('/tag', TagController::class);
    Route::post('/store', [AnswerController::class, 'storeAnswer'])->name('submit');
    Route::get('/answers/{id}/edit', [AnswerController::class, 'editAnswer'])->name('answers');
    Route::post('accept-answer/{id}', [AnswerController::class, 'acceptAnswer'])->name('accept-answer');
    Route::put('/answersupdate/{id}', [AnswerController::class, 'updateAnswer'])->name('answers-update');
    Route::delete('/deleteanswer/{id}', [AnswerController::class, 'answerDelete'])->name('delete-answer');
});

app/Models/Tag.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
class Tag extends Model
{
    use HasFactory;
    protected $fillable=[
        'tag','user_id'
    ];
    public function tagUser(){
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/TagController.php
<?php
namespace App\Http\Controllers;
use App\Http\Requests\TagStore;
use App\Models\Tag;
use Illuminate\Http\Request;
class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags=Tag::paginate(5);
        return view('tags.index',compact('tags'))->with('i', (request()->input('page', 1) - 1) * 5); 
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TagStore $request)
    {
        Tag::create($request->all());
        return redirect()->route('tag.index')->with('success','Tag added successfully.');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        // dd($id);
        // $tag=Tag::find($id);
        // dd($tag);
        return view('tags.edit',compact('tag'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TagStore $request, Tag $tag)
    {
        $data=$request->all(); 
        $tag->update($data);
        return redirect()->route('tag.index')->with('success','Tag updated successfully.');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        $tag->delete();
        return redirect()->route('tag.index')->with('success','Tags deleted successfully');
    }
}

resources/views/tags/create.blade.php
@extends('layouts.admin.app')
@section('content')
    <style>
        label.error {
            color: #dc3545;
            font-size: 20px;
        }
    </style>
    <div class="container-fluid px-4">
        {{-- @if (isset($tag)) --}}
            {{-- <h1 class="mt-4">Edit Tags</h1> --}}
        {{-- @else --}}
            <h1 class="mt-4">Add Tags</h1>
        {{-- @endifs --}}
        <ol class="breadcrumb mb-4">
            <a class="btn btn-primary" href="{{ route('tag.index') }}"> Back</a>
        </ol>
        <form 
        id="regtagForm" action="{{ route('tag.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <input type="hidden" name="user_id" value="{{ Auth::user()->id }}">
                    <div class="form-group">
                        <label for="tag">
                            <strong>Tags<span class="text-danger">*</span></strong>
                        </label>
                        <input type="text" id="tags" name="tag" class="form-control" placeholder="Enter Tag"
                            value="@if (isset($tag)) {{ $tag }}@else{{ old('tag') }} @endif">
                        @if ($errors->has('tag'))
                            <span class="text-danger">{{ $errors->first('tag') }}</span>
                        @endif
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
        </form>
    </div>
    <!-- <script src="{{ asset('Jquery/crud_validation.js') }}?t={{ time() }}"></script> -->
@endsection

resources/views/tags/edit.blade.php
@extends('layouts.admin.app')
@section('content')
<style>
    label.error {
        color: #dc3545;
        font-size: 20px;
    }
</style>
<div class="container-fluid px-4">
    <h1 class="mt-4">Edit Tags</h1>
    <ol class="breadcrumb mb-4">
        <a class="btn btn-primary" href="{{ route('tag.index') }}"> Back</a>
    </ol>
    <form id="edittagForm" action="{{ route('tag.update',$tag->id) }}" method="POST">
        {{-- {{ route('tag.update',$tag->id) }} --}}
        @csrf
        @method('PUT')
        {{-- {{ dd($tag) }} --}}
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <input type="hidden" name="user_id" value="{{ Auth::user()->id }}">
                <div class="form-group">
                    <label for="tag">
                        <strong>Tags<span class="text-danger">*</span></strong>
                    </label>
                    <input type="text" id="tags" name="tag" class="form-control" placeholder="Enter Tag"
                        value="{{ $tag->tag }}">
                    @if ($errors->has('tag'))
                    <span class="text-danger">{{ $errors->first('tag') }}</span>
                    @endif
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
    </form>
</div>
<!-- <script src="{{ asset('Jquery/crud_validation.js') }}?t={{ time() }}"></script> -->
@endsection

resources/views/tags/index.blade.php
@extends('layouts.admin.app')
@section('content')
    <div class="container pt-4">
        <h1 class="mt-2">Add Tags</h1>
        {{-- <ol class="breadcrumb">
            <li class="breadcrumb-item active">add tags for questions</li>
            <!-- <li class="breadcrumb-item active">Dashboard</li> -->
        </ol> --}}
    </div>
    <div class="container">
        <a class="btn btn-primary" href="{{ route('tag.create') }}"> Add Tags </a>
        <ol class="breadcrumb mt-2">
            <li class="breadcrumb-item active">add tags for question's suggestions</li>
            <!-- <li class="breadcrumb-item active">Dashboard</li> -->
        </ol>
    </div>
    <div>
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
    </div>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Tag List
        </div>
        <div class="card-body">
            <table id="datatablesSimple" class="table table-bordered">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Tags</th>
                        <th>Action</th>
                    </tr>
                </thead>
                @foreach ($tags as $tag)
                    <tr>
                        <td>{{ ++$i }}</td>
                        <td> <a class="flex--item s-tag" href="#">{{ $tag->tag }}</a></td>
                        <td>
                            <form action="{{ route('tag.destroy', $tag->id) }}" method="POST">
                                <a class="btn btn-primary" href="{{ route('tag.edit', $tag) }}">Edit</a>
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </table>
        </div>
    </div>
    {{ $tags->links() }}
@endsection